fix: use semantic versions for charts in commit releases (#59509)
Currently, our commit releases produce charts with non-semantic version
numbers. This trips up helm4 linting:

```
 ==> Linting v1.30-alpha.f44b4795/charts/istiod
[WARNING] Chart.yaml: version '1.30-alpha.f44b47959894b1f460d9e0cc301578ce77619bfc' is not a valid SemVerV2
[...snip...]
Error: 5 chart(s) linted, 1 chart(s) failed
```

We don't run into it in our CI because we never commit these version
numbers but only push them as part of the helm chart artifacts, but IMO
we should fix it especially as we're using helm4 with ``--strict`
linting ourselves.